[2020-04-07 16:04:11,053] {scheduler_job.py:153} INFO - Started process (PID=63368) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:04:11,060] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:04:11,061] {logging_mixin.py:112} INFO - [2020-04-07 16:04:11,061] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:04:11,070] {logging_mixin.py:112} INFO - [2020-04-07 16:04:11,065] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:04:11,070] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:04:11,081] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.027 seconds
[2020-04-07 16:05:21,257] {scheduler_job.py:153} INFO - Started process (PID=63407) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:05:21,265] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:05:21,266] {logging_mixin.py:112} INFO - [2020-04-07 16:05:21,265] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:05:21,272] {logging_mixin.py:112} INFO - [2020-04-07 16:05:21,269] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:05:21,273] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:05:21,286] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.029 seconds
[2020-04-07 16:06:31,480] {scheduler_job.py:153} INFO - Started process (PID=63446) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:06:31,488] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:06:31,489] {logging_mixin.py:112} INFO - [2020-04-07 16:06:31,489] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:06:31,494] {logging_mixin.py:112} INFO - [2020-04-07 16:06:31,493] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:06:31,495] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:06:31,514] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.033 seconds
[2020-04-07 16:07:41,697] {scheduler_job.py:153} INFO - Started process (PID=63485) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:07:41,703] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:07:41,704] {logging_mixin.py:112} INFO - [2020-04-07 16:07:41,703] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:07:41,708] {logging_mixin.py:112} INFO - [2020-04-07 16:07:41,707] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:07:41,709] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:07:41,726] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.030 seconds
[2020-04-07 16:08:51,891] {scheduler_job.py:153} INFO - Started process (PID=63525) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:08:51,896] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:08:51,897] {logging_mixin.py:112} INFO - [2020-04-07 16:08:51,897] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:08:51,901] {logging_mixin.py:112} INFO - [2020-04-07 16:08:51,900] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:08:51,902] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:08:51,912] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.021 seconds
[2020-04-07 16:10:02,095] {scheduler_job.py:153} INFO - Started process (PID=63564) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:10:02,101] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:10:02,102] {logging_mixin.py:112} INFO - [2020-04-07 16:10:02,102] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:10:02,106] {logging_mixin.py:112} INFO - [2020-04-07 16:10:02,105] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:10:02,106] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:10:02,122] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.027 seconds
[2020-04-07 16:11:12,292] {scheduler_job.py:153} INFO - Started process (PID=63604) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:11:12,299] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:11:12,300] {logging_mixin.py:112} INFO - [2020-04-07 16:11:12,299] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:11:12,304] {logging_mixin.py:112} INFO - [2020-04-07 16:11:12,303] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:11:12,304] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:11:12,320] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.028 seconds
[2020-04-07 16:12:22,489] {scheduler_job.py:153} INFO - Started process (PID=63649) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:12:22,496] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:12:22,497] {logging_mixin.py:112} INFO - [2020-04-07 16:12:22,496] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:12:22,502] {logging_mixin.py:112} INFO - [2020-04-07 16:12:22,501] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:12:22,503] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:12:22,513] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.024 seconds
[2020-04-07 16:13:32,696] {scheduler_job.py:153} INFO - Started process (PID=63691) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:13:32,702] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:13:32,703] {logging_mixin.py:112} INFO - [2020-04-07 16:13:32,703] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:13:32,707] {logging_mixin.py:112} INFO - [2020-04-07 16:13:32,706] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:13:32,707] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:13:32,718] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.022 seconds
[2020-04-07 16:14:42,888] {scheduler_job.py:153} INFO - Started process (PID=63729) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:14:42,895] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:14:42,896] {logging_mixin.py:112} INFO - [2020-04-07 16:14:42,895] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:14:42,899] {logging_mixin.py:112} INFO - [2020-04-07 16:14:42,898] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:14:42,900] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:14:42,915] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.027 seconds
[2020-04-07 16:15:53,089] {scheduler_job.py:153} INFO - Started process (PID=63767) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:15:53,096] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:15:53,097] {logging_mixin.py:112} INFO - [2020-04-07 16:15:53,097] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:15:53,102] {logging_mixin.py:112} INFO - [2020-04-07 16:15:53,100] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:15:53,102] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:15:53,113] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.024 seconds
[2020-04-07 16:17:03,277] {scheduler_job.py:153} INFO - Started process (PID=63806) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:17:03,284] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:17:03,284] {logging_mixin.py:112} INFO - [2020-04-07 16:17:03,284] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:17:03,290] {logging_mixin.py:112} INFO - [2020-04-07 16:17:03,288] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:17:03,291] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:17:03,305] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.028 seconds
[2020-04-07 16:18:13,485] {scheduler_job.py:153} INFO - Started process (PID=63844) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:18:13,492] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:18:13,493] {logging_mixin.py:112} INFO - [2020-04-07 16:18:13,492] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:18:13,497] {logging_mixin.py:112} INFO - [2020-04-07 16:18:13,495] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:18:13,497] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:18:13,512] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.028 seconds
[2020-04-07 16:19:23,696] {scheduler_job.py:153} INFO - Started process (PID=63883) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:19:23,704] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:19:23,705] {logging_mixin.py:112} INFO - [2020-04-07 16:19:23,704] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:19:23,709] {logging_mixin.py:112} INFO - [2020-04-07 16:19:23,707] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:19:23,710] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:19:23,721] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.025 seconds
[2020-04-07 16:20:38,158] {scheduler_job.py:153} INFO - Started process (PID=63955) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:20:38,167] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:20:38,168] {logging_mixin.py:112} INFO - [2020-04-07 16:20:38,168] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:20:38,179] {logging_mixin.py:112} INFO - [2020-04-07 16:20:38,176] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:20:38,179] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:20:38,195] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.038 seconds
[2020-04-07 16:43:02,035] {scheduler_job.py:153} INFO - Started process (PID=64051) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:43:02,042] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:43:02,043] {logging_mixin.py:112} INFO - [2020-04-07 16:43:02,042] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:43:02,047] {logging_mixin.py:112} INFO - [2020-04-07 16:43:02,046] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:43:02,048] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:43:02,059] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.024 seconds
[2020-04-07 16:43:24,298] {scheduler_job.py:153} INFO - Started process (PID=64127) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:43:24,304] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:43:24,305] {logging_mixin.py:112} INFO - [2020-04-07 16:43:24,304] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:43:24,309] {logging_mixin.py:112} INFO - [2020-04-07 16:43:24,307] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:43:24,309] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:43:24,318] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.021 seconds
[2020-04-07 16:44:20,275] {scheduler_job.py:153} INFO - Started process (PID=64173) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:44:20,285] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:44:20,286] {logging_mixin.py:112} INFO - [2020-04-07 16:44:20,286] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:44:20,292] {logging_mixin.py:112} INFO - [2020-04-07 16:44:20,290] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:44:20,293] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:44:20,306] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.031 seconds
[2020-04-07 16:45:30,570] {scheduler_job.py:153} INFO - Started process (PID=64212) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:46:59,017] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 16:46:59,019] {logging_mixin.py:112} INFO - [2020-04-07 16:46:59,019] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:46:59,027] {logging_mixin.py:112} INFO - [2020-04-07 16:46:59,024] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 16:46:59,029] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 16:46:59,164] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 88.593 seconds
[2020-04-07 17:25:06,087] {scheduler_job.py:153} INFO - Started process (PID=64277) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:25:06,095] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:25:06,097] {logging_mixin.py:112} INFO - [2020-04-07 17:25:06,096] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:25:06,103] {logging_mixin.py:112} INFO - [2020-04-07 17:25:06,101] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:25:06,104] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:25:06,119] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.032 seconds
[2020-04-07 17:26:14,392] {scheduler_job.py:153} INFO - Started process (PID=64318) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:26:14,398] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:26:14,399] {logging_mixin.py:112} INFO - [2020-04-07 17:26:14,399] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:26:14,404] {logging_mixin.py:112} INFO - [2020-04-07 17:26:14,402] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:26:14,404] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:26:14,419] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.026 seconds
[2020-04-07 17:27:33,479] {scheduler_job.py:153} INFO - Started process (PID=64362) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:27:38,485] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:27:38,486] {logging_mixin.py:112} INFO - [2020-04-07 17:27:38,486] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:27:38,495] {logging_mixin.py:112} INFO - [2020-04-07 17:27:38,491] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:27:38,496] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:27:38,507] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 5.028 seconds
[2020-04-07 17:33:29,807] {scheduler_job.py:153} INFO - Started process (PID=64426) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:33:32,022] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:33:32,023] {logging_mixin.py:112} INFO - [2020-04-07 17:33:32,023] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:33:32,030] {logging_mixin.py:112} INFO - [2020-04-07 17:33:32,029] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:33:32,031] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:33:32,047] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 2.239 seconds
[2020-04-07 17:34:06,214] {scheduler_job.py:153} INFO - Started process (PID=64477) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:34:06,222] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:34:06,223] {logging_mixin.py:112} INFO - [2020-04-07 17:34:06,222] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:34:06,226] {logging_mixin.py:112} INFO - [2020-04-07 17:34:06,225] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:34:06,227] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:34:06,239] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.025 seconds
[2020-04-07 17:35:16,656] {scheduler_job.py:153} INFO - Started process (PID=64516) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:35:16,663] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:35:16,664] {logging_mixin.py:112} INFO - [2020-04-07 17:35:16,663] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:35:16,668] {logging_mixin.py:112} INFO - [2020-04-07 17:35:16,667] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:35:16,668] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:35:16,684] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.028 seconds
[2020-04-07 17:36:52,674] {scheduler_job.py:153} INFO - Started process (PID=64570) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:36:52,684] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:36:52,685] {logging_mixin.py:112} INFO - [2020-04-07 17:36:52,685] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:36:52,690] {logging_mixin.py:112} INFO - [2020-04-07 17:36:52,689] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:36:52,690] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:36:52,703] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.030 seconds
[2020-04-07 17:37:38,867] {scheduler_job.py:153} INFO - Started process (PID=64621) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:37:38,873] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:37:38,874] {logging_mixin.py:112} INFO - [2020-04-07 17:37:38,873] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:37:38,878] {logging_mixin.py:112} INFO - [2020-04-07 17:37:38,877] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:37:38,878] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:37:38,890] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.023 seconds
[2020-04-07 17:38:49,026] {scheduler_job.py:153} INFO - Started process (PID=64662) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:38:49,034] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:38:49,035] {logging_mixin.py:112} INFO - [2020-04-07 17:38:49,034] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:38:49,042] {logging_mixin.py:112} INFO - [2020-04-07 17:38:49,039] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:38:49,043] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:38:49,053] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.027 seconds
[2020-04-07 17:39:59,198] {scheduler_job.py:153} INFO - Started process (PID=64701) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:39:59,213] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:39:59,214] {logging_mixin.py:112} INFO - [2020-04-07 17:39:59,213] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:39:59,220] {logging_mixin.py:112} INFO - [2020-04-07 17:39:59,218] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:39:59,220] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:39:59,230] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.032 seconds
[2020-04-07 17:41:09,404] {scheduler_job.py:153} INFO - Started process (PID=64752) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:41:09,412] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:41:09,413] {logging_mixin.py:112} INFO - [2020-04-07 17:41:09,412] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:41:09,417] {logging_mixin.py:112} INFO - [2020-04-07 17:41:09,416] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:41:09,418] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:41:09,428] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.024 seconds
[2020-04-07 17:42:19,600] {scheduler_job.py:153} INFO - Started process (PID=64791) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:42:19,608] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:42:19,609] {logging_mixin.py:112} INFO - [2020-04-07 17:42:19,608] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:42:19,613] {logging_mixin.py:112} INFO - [2020-04-07 17:42:19,612] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:42:19,613] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:42:19,629] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.028 seconds
[2020-04-07 17:43:29,798] {scheduler_job.py:153} INFO - Started process (PID=64829) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:43:29,805] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:43:29,806] {logging_mixin.py:112} INFO - [2020-04-07 17:43:29,805] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:43:29,811] {logging_mixin.py:112} INFO - [2020-04-07 17:43:29,809] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:43:29,812] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:43:29,821] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.023 seconds
[2020-04-07 17:44:40,007] {scheduler_job.py:153} INFO - Started process (PID=64878) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:44:40,016] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:44:40,017] {logging_mixin.py:112} INFO - [2020-04-07 17:44:40,017] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:44:40,027] {logging_mixin.py:112} INFO - [2020-04-07 17:44:40,022] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:44:40,028] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:44:40,041] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.034 seconds
[2020-04-07 17:45:50,203] {scheduler_job.py:153} INFO - Started process (PID=64921) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:45:50,209] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:45:50,210] {logging_mixin.py:112} INFO - [2020-04-07 17:45:50,209] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:45:50,214] {logging_mixin.py:112} INFO - [2020-04-07 17:45:50,213] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:45:50,215] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:45:50,225] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.022 seconds
[2020-04-07 17:47:00,371] {scheduler_job.py:153} INFO - Started process (PID=64959) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:47:00,383] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:47:00,385] {logging_mixin.py:112} INFO - [2020-04-07 17:47:00,384] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:47:00,393] {logging_mixin.py:112} INFO - [2020-04-07 17:47:00,390] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:47:00,393] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:47:00,405] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.034 seconds
[2020-04-07 17:48:10,582] {scheduler_job.py:153} INFO - Started process (PID=64998) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:48:10,588] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:48:10,589] {logging_mixin.py:112} INFO - [2020-04-07 17:48:10,589] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:48:10,593] {logging_mixin.py:112} INFO - [2020-04-07 17:48:10,592] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:48:10,594] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:48:10,603] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.021 seconds
[2020-04-07 17:49:20,762] {scheduler_job.py:153} INFO - Started process (PID=65037) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:49:20,768] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:49:20,768] {logging_mixin.py:112} INFO - [2020-04-07 17:49:20,768] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:49:20,772] {logging_mixin.py:112} INFO - [2020-04-07 17:49:20,771] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:49:20,772] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:49:20,788] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.026 seconds
[2020-04-07 17:50:30,981] {scheduler_job.py:153} INFO - Started process (PID=65075) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:50:30,986] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:50:30,987] {logging_mixin.py:112} INFO - [2020-04-07 17:50:30,987] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:50:30,991] {logging_mixin.py:112} INFO - [2020-04-07 17:50:30,990] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:50:30,991] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:50:31,003] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.023 seconds
[2020-04-07 17:51:41,327] {scheduler_job.py:153} INFO - Started process (PID=65122) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:51:41,334] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:51:41,335] {logging_mixin.py:112} INFO - [2020-04-07 17:51:41,335] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:51:41,341] {logging_mixin.py:112} INFO - [2020-04-07 17:51:41,339] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:51:41,341] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:51:41,355] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.028 seconds
[2020-04-07 17:52:51,621] {scheduler_job.py:153} INFO - Started process (PID=65161) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:52:51,627] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:52:51,628] {logging_mixin.py:112} INFO - [2020-04-07 17:52:51,627] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:52:51,632] {logging_mixin.py:112} INFO - [2020-04-07 17:52:51,631] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:52:51,633] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:52:51,648] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.027 seconds
[2020-04-07 17:54:01,917] {scheduler_job.py:153} INFO - Started process (PID=65199) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:54:01,923] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:54:01,924] {logging_mixin.py:112} INFO - [2020-04-07 17:54:01,923] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:54:01,928] {logging_mixin.py:112} INFO - [2020-04-07 17:54:01,927] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:54:01,928] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:54:01,943] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.026 seconds
[2020-04-07 17:55:12,329] {scheduler_job.py:153} INFO - Started process (PID=65240) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:55:12,334] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:55:12,335] {logging_mixin.py:112} INFO - [2020-04-07 17:55:12,335] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:55:12,339] {logging_mixin.py:112} INFO - [2020-04-07 17:55:12,338] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:55:12,339] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:55:12,349] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.020 seconds
[2020-04-07 17:56:22,622] {scheduler_job.py:153} INFO - Started process (PID=65289) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:56:22,627] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:56:22,628] {logging_mixin.py:112} INFO - [2020-04-07 17:56:22,628] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:56:22,632] {logging_mixin.py:112} INFO - [2020-04-07 17:56:22,631] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:56:22,632] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:56:22,648] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.027 seconds
[2020-04-07 17:57:32,841] {scheduler_job.py:153} INFO - Started process (PID=65327) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:57:32,846] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:57:32,847] {logging_mixin.py:112} INFO - [2020-04-07 17:57:32,847] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:57:32,851] {logging_mixin.py:112} INFO - [2020-04-07 17:57:32,850] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:57:32,852] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:57:32,865] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.025 seconds
[2020-04-07 17:58:43,063] {scheduler_job.py:153} INFO - Started process (PID=65365) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:58:43,068] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:58:43,069] {logging_mixin.py:112} INFO - [2020-04-07 17:58:43,069] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:58:43,073] {logging_mixin.py:112} INFO - [2020-04-07 17:58:43,072] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:58:43,073] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:58:43,083] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.020 seconds
[2020-04-07 17:59:53,262] {scheduler_job.py:153} INFO - Started process (PID=65404) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:59:53,267] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 17:59:53,268] {logging_mixin.py:112} INFO - [2020-04-07 17:59:53,268] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:59:53,272] {logging_mixin.py:112} INFO - [2020-04-07 17:59:53,271] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 17:59:53,272] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 17:59:53,287] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.025 seconds
[2020-04-07 18:01:03,499] {scheduler_job.py:153} INFO - Started process (PID=65443) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:01:03,506] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 18:01:03,507] {logging_mixin.py:112} INFO - [2020-04-07 18:01:03,507] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:01:03,511] {logging_mixin.py:112} INFO - [2020-04-07 18:01:03,510] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:01:03,511] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:01:03,523] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.023 seconds
[2020-04-07 18:02:13,846] {scheduler_job.py:153} INFO - Started process (PID=65491) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:02:13,852] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 18:02:13,853] {logging_mixin.py:112} INFO - [2020-04-07 18:02:13,852] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:02:13,857] {logging_mixin.py:112} INFO - [2020-04-07 18:02:13,855] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:02:13,858] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:02:13,867] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.021 seconds
[2020-04-07 18:03:24,210] {scheduler_job.py:153} INFO - Started process (PID=65530) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:03:24,217] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 18:03:24,218] {logging_mixin.py:112} INFO - [2020-04-07 18:03:24,218] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:03:24,225] {logging_mixin.py:112} INFO - [2020-04-07 18:03:24,223] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:03:24,225] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:03:24,242] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.032 seconds
[2020-04-07 18:04:34,600] {scheduler_job.py:153} INFO - Started process (PID=65569) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:04:34,606] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 18:04:34,607] {logging_mixin.py:112} INFO - [2020-04-07 18:04:34,607] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:04:34,611] {logging_mixin.py:112} INFO - [2020-04-07 18:04:34,610] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:04:34,611] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:04:34,626] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.026 seconds
[2020-04-07 18:05:44,998] {scheduler_job.py:153} INFO - Started process (PID=65608) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:05:45,003] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 18:05:45,005] {logging_mixin.py:112} INFO - [2020-04-07 18:05:45,004] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:05:45,008] {logging_mixin.py:112} INFO - [2020-04-07 18:05:45,007] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:05:45,009] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:05:45,018] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.020 seconds
[2020-04-07 18:38:47,035] {scheduler_job.py:153} INFO - Started process (PID=65683) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:38:47,067] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 18:38:47,070] {logging_mixin.py:112} INFO - [2020-04-07 18:38:47,069] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:38:47,089] {logging_mixin.py:112} INFO - [2020-04-07 18:38:47,079] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:38:47,090] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:38:47,115] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.080 seconds
[2020-04-07 18:39:55,229] {scheduler_job.py:153} INFO - Started process (PID=65733) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:39:55,238] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 18:39:55,240] {logging_mixin.py:112} INFO - [2020-04-07 18:39:55,239] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:39:55,246] {logging_mixin.py:112} INFO - [2020-04-07 18:39:55,245] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:39:55,246] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:39:55,259] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.030 seconds
[2020-04-07 18:41:05,394] {scheduler_job.py:153} INFO - Started process (PID=65773) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:41:05,401] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 18:41:05,403] {logging_mixin.py:112} INFO - [2020-04-07 18:41:05,402] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:41:05,409] {logging_mixin.py:112} INFO - [2020-04-07 18:41:05,407] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:41:05,409] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:41:05,422] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.028 seconds
[2020-04-07 18:42:15,594] {scheduler_job.py:153} INFO - Started process (PID=65813) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:42:15,600] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 18:42:15,601] {logging_mixin.py:112} INFO - [2020-04-07 18:42:15,601] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:42:15,605] {logging_mixin.py:112} INFO - [2020-04-07 18:42:15,604] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:42:15,605] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:42:15,616] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.022 seconds
[2020-04-07 18:43:37,351] {scheduler_job.py:153} INFO - Started process (PID=65860) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:43:37,357] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 18:43:37,358] {logging_mixin.py:112} INFO - [2020-04-07 18:43:37,358] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:43:37,362] {logging_mixin.py:112} INFO - [2020-04-07 18:43:37,361] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:43:37,362] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:43:37,378] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.027 seconds
[2020-04-07 18:45:09,287] {scheduler_job.py:153} INFO - Started process (PID=65912) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:45:09,293] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 18:45:09,294] {logging_mixin.py:112} INFO - [2020-04-07 18:45:09,293] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:45:09,297] {logging_mixin.py:112} INFO - [2020-04-07 18:45:09,296] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:45:09,298] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:45:09,313] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.026 seconds
[2020-04-07 18:46:29,853] {scheduler_job.py:153} INFO - Started process (PID=66220) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:46:29,862] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 18:46:29,863] {logging_mixin.py:112} INFO - [2020-04-07 18:46:29,863] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:46:29,869] {logging_mixin.py:112} INFO - [2020-04-07 18:46:29,867] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:46:29,870] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:46:29,883] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.030 seconds
[2020-04-07 18:47:40,159] {scheduler_job.py:153} INFO - Started process (PID=67646) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:47:40,165] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 18:47:40,166] {logging_mixin.py:112} INFO - [2020-04-07 18:47:40,165] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:47:40,170] {logging_mixin.py:112} INFO - [2020-04-07 18:47:40,169] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:47:40,171] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:47:40,182] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.023 seconds
[2020-04-07 18:48:50,494] {scheduler_job.py:153} INFO - Started process (PID=67684) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:48:50,500] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 18:48:50,501] {logging_mixin.py:112} INFO - [2020-04-07 18:48:50,500] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:48:50,505] {logging_mixin.py:112} INFO - [2020-04-07 18:48:50,504] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:48:50,506] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:48:50,515] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.021 seconds
[2020-04-07 18:50:00,820] {scheduler_job.py:153} INFO - Started process (PID=67723) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:50:00,826] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 18:50:00,827] {logging_mixin.py:112} INFO - [2020-04-07 18:50:00,827] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:50:00,832] {logging_mixin.py:112} INFO - [2020-04-07 18:50:00,830] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:50:00,832] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:50:00,848] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.028 seconds
[2020-04-07 18:51:22,594] {scheduler_job.py:153} INFO - Started process (PID=67767) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:51:22,601] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 18:51:22,602] {logging_mixin.py:112} INFO - [2020-04-07 18:51:22,601] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:51:22,606] {logging_mixin.py:112} INFO - [2020-04-07 18:51:22,605] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:51:22,606] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:51:22,622] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.028 seconds
[2020-04-07 18:52:43,356] {scheduler_job.py:153} INFO - Started process (PID=67813) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:52:43,364] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 18:52:43,365] {logging_mixin.py:112} INFO - [2020-04-07 18:52:43,365] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:52:43,369] {logging_mixin.py:112} INFO - [2020-04-07 18:52:43,368] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 18:52:43,369] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 18:52:43,385] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.029 seconds
[2020-04-07 19:26:43,171] {scheduler_job.py:153} INFO - Started process (PID=67873) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:26:43,185] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:26:43,187] {logging_mixin.py:112} INFO - [2020-04-07 19:26:43,186] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:26:43,191] {logging_mixin.py:112} INFO - [2020-04-07 19:26:43,190] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:26:43,192] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:26:43,202] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.031 seconds
[2020-04-07 19:27:53,377] {scheduler_job.py:153} INFO - Started process (PID=67912) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:27:53,385] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:27:53,386] {logging_mixin.py:112} INFO - [2020-04-07 19:27:53,385] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:27:53,391] {logging_mixin.py:112} INFO - [2020-04-07 19:27:53,390] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:27:53,392] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:27:53,402] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.026 seconds
[2020-04-07 19:29:03,581] {scheduler_job.py:153} INFO - Started process (PID=67968) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:29:03,588] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:29:03,589] {logging_mixin.py:112} INFO - [2020-04-07 19:29:03,589] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:29:03,594] {logging_mixin.py:112} INFO - [2020-04-07 19:29:03,593] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:29:03,594] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:29:03,606] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.025 seconds
[2020-04-07 19:30:13,757] {scheduler_job.py:153} INFO - Started process (PID=68010) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:30:13,763] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:30:13,764] {logging_mixin.py:112} INFO - [2020-04-07 19:30:13,764] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:30:13,770] {logging_mixin.py:112} INFO - [2020-04-07 19:30:13,768] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:30:13,771] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:30:13,782] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.025 seconds
[2020-04-07 19:31:23,958] {scheduler_job.py:153} INFO - Started process (PID=68048) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:31:23,965] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:31:23,966] {logging_mixin.py:112} INFO - [2020-04-07 19:31:23,966] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:31:23,971] {logging_mixin.py:112} INFO - [2020-04-07 19:31:23,969] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:31:23,971] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:31:23,980] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.023 seconds
[2020-04-07 19:32:34,151] {scheduler_job.py:153} INFO - Started process (PID=68087) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:32:34,157] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:32:34,158] {logging_mixin.py:112} INFO - [2020-04-07 19:32:34,157] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:32:34,162] {logging_mixin.py:112} INFO - [2020-04-07 19:32:34,161] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:32:34,162] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:32:34,178] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.027 seconds
[2020-04-07 19:33:44,375] {scheduler_job.py:153} INFO - Started process (PID=68126) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:33:44,382] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:33:44,383] {logging_mixin.py:112} INFO - [2020-04-07 19:33:44,382] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:33:44,387] {logging_mixin.py:112} INFO - [2020-04-07 19:33:44,385] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:33:44,387] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:33:44,402] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.027 seconds
[2020-04-07 19:34:54,572] {scheduler_job.py:153} INFO - Started process (PID=68165) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:34:54,578] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:34:54,579] {logging_mixin.py:112} INFO - [2020-04-07 19:34:54,578] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:34:54,582] {logging_mixin.py:112} INFO - [2020-04-07 19:34:54,581] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:34:54,583] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:34:54,593] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.021 seconds
[2020-04-07 19:36:04,841] {scheduler_job.py:153} INFO - Started process (PID=68216) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:36:04,849] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:36:04,850] {logging_mixin.py:112} INFO - [2020-04-07 19:36:04,849] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:36:04,856] {logging_mixin.py:112} INFO - [2020-04-07 19:36:04,854] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:36:04,856] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:36:04,867] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.026 seconds
[2020-04-07 19:37:15,108] {scheduler_job.py:153} INFO - Started process (PID=68254) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:37:15,114] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:37:15,115] {logging_mixin.py:112} INFO - [2020-04-07 19:37:15,114] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:37:15,120] {logging_mixin.py:112} INFO - [2020-04-07 19:37:15,118] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:37:15,120] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:37:15,129] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.021 seconds
[2020-04-07 19:38:25,464] {scheduler_job.py:153} INFO - Started process (PID=68293) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:38:25,470] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:38:25,471] {logging_mixin.py:112} INFO - [2020-04-07 19:38:25,471] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:38:25,475] {logging_mixin.py:112} INFO - [2020-04-07 19:38:25,474] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:38:25,475] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:38:25,485] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.021 seconds
[2020-04-07 19:39:35,783] {scheduler_job.py:153} INFO - Started process (PID=68339) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:39:35,789] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:39:35,790] {logging_mixin.py:112} INFO - [2020-04-07 19:39:35,790] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:39:35,794] {logging_mixin.py:112} INFO - [2020-04-07 19:39:35,793] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:39:35,794] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:39:35,810] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.026 seconds
[2020-04-07 19:40:45,980] {scheduler_job.py:153} INFO - Started process (PID=68379) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:40:45,993] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:40:45,995] {logging_mixin.py:112} INFO - [2020-04-07 19:40:45,994] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:40:46,004] {logging_mixin.py:112} INFO - [2020-04-07 19:40:46,000] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:40:46,004] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:40:46,015] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.035 seconds
[2020-04-07 19:41:56,171] {scheduler_job.py:153} INFO - Started process (PID=68431) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:41:56,178] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:41:56,179] {logging_mixin.py:112} INFO - [2020-04-07 19:41:56,178] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:41:56,185] {logging_mixin.py:112} INFO - [2020-04-07 19:41:56,183] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:41:56,185] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:41:56,196] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.026 seconds
[2020-04-07 19:43:06,363] {scheduler_job.py:153} INFO - Started process (PID=68469) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:43:06,370] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:43:06,371] {logging_mixin.py:112} INFO - [2020-04-07 19:43:06,371] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:43:06,376] {logging_mixin.py:112} INFO - [2020-04-07 19:43:06,374] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:43:06,376] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:43:06,386] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.023 seconds
[2020-04-07 19:44:16,585] {scheduler_job.py:153} INFO - Started process (PID=68507) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:44:16,591] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:44:16,592] {logging_mixin.py:112} INFO - [2020-04-07 19:44:16,592] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:44:16,596] {logging_mixin.py:112} INFO - [2020-04-07 19:44:16,595] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:44:16,596] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:44:16,613] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.028 seconds
[2020-04-07 19:45:26,803] {scheduler_job.py:153} INFO - Started process (PID=68550) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:45:26,808] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:45:26,809] {logging_mixin.py:112} INFO - [2020-04-07 19:45:26,809] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:45:26,813] {logging_mixin.py:112} INFO - [2020-04-07 19:45:26,812] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:45:26,814] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:45:26,824] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.021 seconds
[2020-04-07 19:46:37,005] {scheduler_job.py:153} INFO - Started process (PID=68588) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:46:37,010] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:46:37,011] {logging_mixin.py:112} INFO - [2020-04-07 19:46:37,011] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:46:37,015] {logging_mixin.py:112} INFO - [2020-04-07 19:46:37,014] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:46:37,015] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:46:37,030] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.026 seconds
[2020-04-07 19:47:47,206] {scheduler_job.py:153} INFO - Started process (PID=68626) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:47:47,211] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:47:47,212] {logging_mixin.py:112} INFO - [2020-04-07 19:47:47,212] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:47:47,216] {logging_mixin.py:112} INFO - [2020-04-07 19:47:47,215] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:47:47,216] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:47:47,232] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.026 seconds
[2020-04-07 19:48:57,392] {scheduler_job.py:153} INFO - Started process (PID=68669) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:48:57,398] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:48:57,398] {logging_mixin.py:112} INFO - [2020-04-07 19:48:57,398] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:48:57,402] {logging_mixin.py:112} INFO - [2020-04-07 19:48:57,401] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:48:57,403] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:48:57,412] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.020 seconds
[2020-04-07 19:50:07,596] {scheduler_job.py:153} INFO - Started process (PID=68718) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:50:07,604] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:50:07,605] {logging_mixin.py:112} INFO - [2020-04-07 19:50:07,605] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:50:07,613] {logging_mixin.py:112} INFO - [2020-04-07 19:50:07,611] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:50:07,613] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:50:07,625] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.029 seconds
[2020-04-07 19:51:17,861] {scheduler_job.py:153} INFO - Started process (PID=68763) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:51:17,871] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:51:17,873] {logging_mixin.py:112} INFO - [2020-04-07 19:51:17,872] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:51:17,887] {logging_mixin.py:112} INFO - [2020-04-07 19:51:17,883] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:51:17,888] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:51:17,904] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.043 seconds
[2020-04-07 19:52:28,012] {scheduler_job.py:153} INFO - Started process (PID=68806) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:52:28,020] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:52:28,022] {logging_mixin.py:112} INFO - [2020-04-07 19:52:28,021] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:52:28,031] {logging_mixin.py:112} INFO - [2020-04-07 19:52:28,026] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:52:28,031] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:52:28,045] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.033 seconds
[2020-04-07 19:53:38,231] {scheduler_job.py:153} INFO - Started process (PID=68858) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:53:38,245] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:53:38,246] {logging_mixin.py:112} INFO - [2020-04-07 19:53:38,246] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:53:38,255] {logging_mixin.py:112} INFO - [2020-04-07 19:53:38,252] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:53:38,255] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:53:38,268] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.037 seconds
[2020-04-07 19:54:48,427] {scheduler_job.py:153} INFO - Started process (PID=68923) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:54:48,434] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:54:48,435] {logging_mixin.py:112} INFO - [2020-04-07 19:54:48,435] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:54:48,443] {logging_mixin.py:112} INFO - [2020-04-07 19:54:48,442] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:54:48,444] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:54:48,454] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.027 seconds
[2020-04-07 19:55:58,627] {scheduler_job.py:153} INFO - Started process (PID=68964) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:55:58,635] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:55:58,636] {logging_mixin.py:112} INFO - [2020-04-07 19:55:58,635] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:55:58,640] {logging_mixin.py:112} INFO - [2020-04-07 19:55:58,639] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:55:58,641] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:55:58,650] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.023 seconds
[2020-04-07 19:57:08,842] {scheduler_job.py:153} INFO - Started process (PID=69010) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:57:08,854] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:57:08,855] {logging_mixin.py:112} INFO - [2020-04-07 19:57:08,855] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:57:08,859] {logging_mixin.py:112} INFO - [2020-04-07 19:57:08,858] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:57:08,860] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:57:08,871] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.029 seconds
[2020-04-07 19:58:19,051] {scheduler_job.py:153} INFO - Started process (PID=69048) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:58:19,058] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:58:19,059] {logging_mixin.py:112} INFO - [2020-04-07 19:58:19,059] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:58:19,063] {logging_mixin.py:112} INFO - [2020-04-07 19:58:19,062] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:58:19,064] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:58:19,074] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.022 seconds
[2020-04-07 19:59:29,264] {scheduler_job.py:153} INFO - Started process (PID=69093) to work on /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:59:29,270] {scheduler_job.py:1560} INFO - Processing file /Users/cchavez/dev/airflow_home/dags/airflow_project.py for tasks to queue
[2020-04-07 19:59:29,271] {logging_mixin.py:112} INFO - [2020-04-07 19:59:29,270] {dagbag.py:403} INFO - Filling up the DagBag from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:59:29,279] {logging_mixin.py:112} INFO - [2020-04-07 19:59:29,275] {dagbag.py:246} ERROR - Failed to import: /Users/cchavez/dev/airflow_home/dags/airflow_project.py
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cchavez/dev/airflow_home/dags/airflow_project.py", line 18, in <module>
    Task_I = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2020-04-07 19:59:29,279] {scheduler_job.py:1574} WARNING - No viable dags retrieved from /Users/cchavez/dev/airflow_home/dags/airflow_project.py
[2020-04-07 19:59:29,289] {scheduler_job.py:161} INFO - Processing /Users/cchavez/dev/airflow_home/dags/airflow_project.py took 0.026 seconds
