[2020-04-07 06:58:38,676] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: atp_data03.create_table 2020-04-06T00:00:00+00:00 [queued]>
[2020-04-07 06:58:38,688] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: atp_data03.create_table 2020-04-06T00:00:00+00:00 [queued]>
[2020-04-07 06:58:38,689] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-04-07 06:58:38,689] {taskinstance.py:867} INFO - Starting attempt 1 of 2
[2020-04-07 06:58:38,689] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-04-07 06:58:38,697] {taskinstance.py:887} INFO - Executing <Task(PostgresOperator): create_table> on 2020-04-06T00:00:00+00:00
[2020-04-07 06:58:38,700] {standard_task_runner.py:53} INFO - Started process 47242 to run task
[2020-04-07 06:58:38,765] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: atp_data03.create_table 2020-04-06T00:00:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-04-07 06:58:38,785] {postgres_operator.py:62} INFO - Executing: 
	DROP TABLE IF EXISTS house_prices.test;
    CREATE TABLE house_prices.test
    (
        MSSubClass numeric, 
        MSZoning varchar(255),
        LotFrontage numeric,
        LotArea numeric,
        Street varchar(255), 
        Alley varchar(255),
        LotShape varchar(255),
        LandContour varchar(255),
        Utilities varchar(255),
        LotConfig varchar(255),
        LandSlope varchar(255),
        Neighborhood varchar(255),
        Condition1 varchar(255),
        Condition2 varchar(255),
        BldgType varchar(255),
        HouseStyle varchar(255),
        OverallQual numeric, 
        OverallCond  numeric, 
        YearBuilt  numeric, 
        YearRemodAdd  numeric, 
        RoofStyle varchar(255),
        RoofMatl varchar(255),
        Exterior1st varchar(255),
        Exterior2nd varchar(255),
        MasVnrType varchar(255),
        MasVnrArea  numeric, 
        ExterQual varchar(255),
        ExterCond varchar(255),
        Foundation  varchar(255),
        BsmtQual varchar(255),
        BsmtCond  varchar(255),
        BsmtExposure varchar(255),
        BsmtFinType1 varchar(255),
        BsmtFinSF1 numeric, 
        BsmtFinType2 varchar(255),
        BsmtFinSF2 numeric, 
        BsmtUnfSF numeric,  
        TotalBsmtSF numeric,  
        Heating varchar(255),
        HeatingQC varchar(255),
        CentralAir varchar(255),
        Electrical varchar(255),
        1stFlrSF numeric, 
        2ndFlrSF  numeric, 
        LowQualFinSF  numeric, 
        GrLivArea numeric, 
        BsmtFullBath numeric, 
        BsmtHalfBath numeric, 
        FullBath numeric, 
        HalfBath  numeric, 
        BedroomAbvGr numeric, 
        KitchenAbvGr numeric, 
        KitchenQual varchar(255),
        TotRmsAbvGrd numeric, 
        Functional varchar(255),
        Fireplaces numeric, 
        FireplaceQu varchar(255),
        GarageType varchar(255),
        GarageYrBlt  numeric, 
        GarageFinish varchar(255),
        GarageCars  numeric, 
        GarageArea  numeric, 
        GarageQual varchar(255),
        GarageCond varchar(255),
        PavedDrive varchar(255),
        WoodDeckSF  numeric, 
        OpenPorchSF  numeric, 
        EnclosedPorch numeric, 
        3SsnPorch  numeric, 
        ScreenPorch  numeric, 
        PoolArea numeric, 
        PoolQC varchar(255),
        Fence varchar(255),
        MiscFeature varchar(255),
        MiscVal numeric, 
        MoSold numeric, 
        YrSold numeric, 
        SaleType varchar(255),
        SaleCondition varchar(255),
        SalePrice numeric; 
[2020-04-07 06:58:38,792] {logging_mixin.py:112} INFO - [2020-04-07 06:58:38,791] {base_hook.py:84} INFO - Using connection to: id: postgres_connection. Host: localhost, Port: 5432, Schema: housing_prices, Login: myuser, Password: XXXXXXXX, extra: None
[2020-04-07 06:58:38,799] {taskinstance.py:1128} ERROR - FATAL:  role "myuser" does not exist
Traceback (most recent call last):
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/postgres_operator.py", line 65, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 162, in run
    with closing(self.get_conn()) as conn:
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/hooks/postgres_hook.py", line 93, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/Users/cchavez/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  role "myuser" does not exist

[2020-04-07 06:58:38,804] {taskinstance.py:1151} INFO - Marking task as UP_FOR_RETRY
[2020-04-07 06:58:48,616] {logging_mixin.py:112} INFO - [2020-04-07 06:58:48,615] {local_task_job.py:103} INFO - Task exited with return code 1
